function nodes = createNodes() 
    nodes = [];
    labels = "label:LYING_DOWN";
    %  "location:diameter",
    features = ["audio_naive:mfcc2:std", "proc_gyro:magnitude_stats:percentile50", "watch_acceleration:magnitude_stats:std", "proc_gyro:3d:std_x", "watch_heading:std_cos", "watch_heading:mom4_cos", "raw_acc:magnitude_stats:value_entropy", "audio_naive:mfcc9:std", "raw_acc:magnitude_spectrum:log_energy_band2", "proc_gyro:3d:std_z", "audio_naive:mfcc0:mean", "watch_acceleration:relative_directions:avr_cosine_similarity_lag_range1", "watch_acceleration:relative_directions:avr_cosine_similarity_lag_range2", "proc_gyro:magnitude_stats:value_entropy", "discrete:battery_plugged:missing", "watch_acceleration:spectrum:z_log_energy_band0", "proc_gyro:magnitude_spectrum:log_energy_band2", "watch_heading:mom4_sin", "watch_acceleration:spectrum:z_log_energy_band2", "watch_acceleration:3d:std_x", "raw_acc:magnitude_spectrum:spectral_entropy", "proc_gyro:magnitude_stats:mean", "watch_acceleration:relative_directions:avr_cosine_similarity_lag_range0", "watch_acceleration:magnitude_spectrum:log_energy_band4", "audio_properties:normalization_multiplier", "raw_acc:magnitude_spectrum:log_energy_band1", "proc_gyro:magnitude_stats:time_entropy", "location:best_horizontal_accuracy", "proc_gyro:magnitude_spectrum:log_energy_band3", "watch_acceleration:spectrum:z_log_energy_band4", "audio_naive:mfcc11:std", "discrete:battery_state:is_discharging", "watch_heading:entropy_8bins", "location:log_latitude_range", "audio_naive:mfcc5:std", "watch_acceleration:magnitude_spectrum:spectral_entropy", "raw_acc:3d:std_x", "raw_acc:magnitude_spectrum:log_energy_band3", "proc_gyro:magnitude_stats:moment4", "audio_naive:mfcc10:std", "audio_naive:mfcc7:mean", "audio_naive:mfcc4:std", "audio_naive:mfcc8:std", "watch_acceleration:3d:std_z", "proc_gyro:magnitude_spectrum:log_energy_band1", "discrete:battery_state:is_unplugged", "location:log_diameter", "proc_gyro:magnitude_stats:percentile75", "raw_acc:magnitude_spectrum:log_energy_band4", "watch_acceleration:magnitude_spectrum:log_energy_band3", "raw_acc:magnitude_stats:moment3", "proc_gyro:3d:std_y", "proc_gyro:magnitude_stats:moment3", "watch_acceleration:magnitude_stats:mean", "raw_acc:magnitude_stats:percentile75", "audio_naive:mfcc7:std", "watch_acceleration:magnitude_spectrum:log_energy_band2", "proc_gyro:magnitude_stats:std", "discrete:wifi_status:is_reachable_via_wifi", "audio_naive:mfcc1:std", "discrete:time_of_day:between21and3", "audio_naive:mfcc3:std", "watch_acceleration:relative_directions:avr_cosine_similarity_lag_range3", "watch_acceleration:magnitude_spectrum:log_energy_band1", "audio_naive:mfcc6:std", "audio_naive:mfcc5:mean", "watch_acceleration:spectrum:y_log_energy_band0", "raw_acc:magnitude_stats:moment4", "location:max_speed", "watch_acceleration:spectrum:z_log_energy_band1", "raw_acc:magnitude_stats:std", "watch_acceleration:3d:std_y", "raw_acc:3d:std_z", "watch_acceleration:magnitude_stats:moment4", "raw_acc:magnitude_stats:time_entropy"];
    graphNode = GraphNode(labels, features);
    nodes = [nodes graphNode];
    
    labels = "label:SITTING";
    features = ["proc_gyro:3d:std_x", "audio_naive:mfcc9:std", "raw_acc:magnitude_stats:value_entropy", "raw_acc:magnitude_spectrum:log_energy_band2", "audio_naive:mfcc0:mean", "proc_gyro:magnitude_stats:value_entropy", "proc_gyro:magnitude_spectrum:log_energy_band2", "raw_acc:magnitude_spectrum:spectral_entropy", "proc_gyro:magnitude_stats:mean", "watch_acceleration:spectrum:y_log_energy_band3", "proc_gyro:magnitude_stats:time_entropy", "audio_naive:mfcc11:std", "watch_acceleration:spectrum:y_log_energy_band4", "audio_naive:mfcc5:std", "location:num_valid_updates", "raw_acc:magnitude_spectrum:log_energy_band3", "audio_naive:mfcc10:std", "proc_gyro:magnitude_spectrum:log_energy_band1", "audio_naive:mfcc4:std", "audio_naive:mfcc8:std", "proc_gyro:magnitude_stats:percentile75", "raw_acc:magnitude_stats:moment3", "audio_naive:mfcc12:std", "audio_naive:mfcc7:std", "audio_naive:mfcc1:std", "discrete:time_of_day:between21and3", "audio_naive:mfcc3:std", "audio_naive:mfcc6:std", "audio_naive:mfcc5:mean", "location:max_speed", "raw_acc:magnitude_stats:std"];
    graphNode = GraphNode(labels, features);
    nodes = [nodes graphNode];
    
    labels = "label:FIX_walking";
    features = ["proc_gyro:3d:std_x", "watch_heading:mom4_cos", "raw_acc:magnitude_spectrum:log_energy_band2", "proc_gyro:3d:std_z", "raw_magnet:3d:std_z", "watch_acceleration:spectrum:z_log_energy_band3", "watch_acceleration:relative_directions:avr_cosine_similarity_lag_range1", "raw_acc:3d:std_y", "watch_acceleration:relative_directions:avr_cosine_similarity_lag_range2", "watch_heading:mom4_sin", "watch_acceleration:spectrum:z_log_energy_band2", "watch_acceleration:3d:std_x", "raw_acc:magnitude_spectrum:spectral_entropy", "proc_gyro:magnitude_stats:mean", "watch_acceleration:relative_directions:avr_cosine_similarity_lag_range0", "watch_acceleration:magnitude_spectrum:log_energy_band4", "watch_acceleration:spectrum:z_log_energy_band4", "watch_acceleration:spectrum:y_log_energy_band1", "proc_gyro:magnitude_stats:percentile25", "discrete:battery_state:is_discharging", "watch_heading:entropy_8bins", "audio_properties:max_abs_value", "watch_acceleration:magnitude_stats:moment3", "watch_acceleration:magnitude_stats:percentile75", "raw_magnet:magnitude_spectrum:log_energy_band1", "raw_acc:magnitude_stats:time_entropy", "raw_acc:3d:std_x", "watch_acceleration:magnitude_spectrum:spectral_entropy", "raw_acc:magnitude_spectrum:log_energy_band3", "proc_gyro:magnitude_stats:moment4", "proc_gyro:magnitude_spectrum:log_energy_band1", "watch_acceleration:3d:std_z", "watch_heading:std_sin", "proc_gyro:magnitude_stats:percentile75", "proc_gyro:magnitude_stats:moment3", "watch_acceleration:magnitude_spectrum:log_energy_band3", "raw_acc:magnitude_spectrum:log_energy_band4", "raw_acc:magnitude_stats:moment3", "proc_gyro:3d:std_y", "watch_acceleration:magnitude_stats:mean", "raw_acc:magnitude_stats:percentile75", "proc_gyro:magnitude_stats:std", "watch_acceleration:magnitude_spectrum:log_energy_band2", "discrete:wifi_status:is_reachable_via_wifi", "discrete:time_of_day:between21and3", "watch_acceleration:relative_directions:avr_cosine_similarity_lag_range3", "watch_acceleration:magnitude_spectrum:log_energy_band1", "raw_acc:magnitude_stats:percentile25", "raw_acc:magnitude_stats:moment4", "raw_acc:magnitude_stats:std", "raw_magnet:3d:std_y", "watch_acceleration:3d:std_y", "raw_acc:3d:std_z", "watch_acceleration:magnitude_stats:moment4", "watch_acceleration:spectrum:z_log_energy_band1"];
    graphNode = GraphNode(labels, features);
    nodes = [nodes graphNode];
    
    labels = "label:FIX_running";
    features = ["proc_gyro:3d:std_x", "raw_acc:magnitude_stats:mean", "raw_acc:magnitude_spectrum:log_energy_band2", "proc_gyro:3d:std_z", "watch_acceleration:spectrum:z_log_energy_band3", "watch_acceleration:relative_directions:avr_cosine_similarity_lag_range1", "raw_acc:3d:std_y", "watch_acceleration:relative_directions:avr_cosine_similarity_lag_range2", "watch_acceleration:spectrum:z_log_energy_band2", "watch_acceleration:3d:std_x", "raw_acc:magnitude_spectrum:spectral_entropy", "proc_gyro:magnitude_stats:mean", "watch_acceleration:relative_directions:avr_cosine_similarity_lag_range0", "watch_acceleration:magnitude_spectrum:log_energy_band4", "watch_acceleration:spectrum:z_log_energy_band4", "proc_gyro:magnitude_stats:percentile25", "watch_acceleration:magnitude_stats:moment3", "watch_acceleration:magnitude_stats:percentile75", "raw_acc:3d:std_x", "watch_acceleration:magnitude_spectrum:spectral_entropy", "raw_acc:magnitude_spectrum:log_energy_band3", "proc_gyro:magnitude_stats:percentile75", "raw_acc:magnitude_spectrum:log_energy_band0", "raw_acc:magnitude_spectrum:log_energy_band4", "watch_acceleration:magnitude_spectrum:log_energy_band3", "raw_acc:magnitude_stats:moment3", "proc_gyro:3d:std_y", "watch_acceleration:magnitude_stats:mean", "raw_acc:magnitude_stats:percentile75", "proc_gyro:magnitude_stats:std", "watch_acceleration:magnitude_spectrum:log_energy_band2", "watch_acceleration:magnitude_spectrum:log_energy_band1", "raw_acc:magnitude_stats:moment4", "raw_acc:magnitude_stats:std", "watch_acceleration:3d:std_y", "raw_acc:3d:std_z", "watch_acceleration:magnitude_stats:moment4", "raw_acc:magnitude_stats:time_entropy"];
    graphNode = GraphNode(labels, features);
    nodes = [nodes graphNode];
    
    labels = "label:BICYCLING";
    features = ["proc_gyro:3d:std_x", "raw_acc:magnitude_stats:mean", "raw_acc:magnitude_spectrum:log_energy_band2", "proc_gyro:3d:std_z", "watch_acceleration:spectrum:z_log_energy_band3", "watch_acceleration:relative_directions:avr_cosine_similarity_lag_range1", "raw_acc:3d:std_y", "watch_acceleration:relative_directions:avr_cosine_similarity_lag_range2", "watch_acceleration:spectrum:z_log_energy_band2", "watch_acceleration:3d:std_x", "raw_acc:magnitude_spectrum:spectral_entropy", "proc_gyro:magnitude_stats:mean", "watch_acceleration:relative_directions:avr_cosine_similarity_lag_range0", "watch_acceleration:magnitude_spectrum:log_energy_band4", "raw_acc:magnitude_spectrum:log_energy_band1", "watch_acceleration:spectrum:y_log_energy_band3", "watch_acceleration:magnitude_stats:percentile50", "watch_acceleration:spectrum:z_log_energy_band4", "watch_acceleration:spectrum:y_log_energy_band1", "watch_acceleration:spectrum:y_log_energy_band4", "watch_acceleration:spectrum:x_log_energy_band4", "proc_gyro:magnitude_stats:percentile25", "discrete:battery_state:is_discharging", "audio_properties:max_abs_value", "watch_acceleration:magnitude_stats:moment3", "watch_acceleration:magnitude_stats:percentile75", "raw_acc:magnitude_stats:time_entropy", "raw_acc:3d:std_x", "watch_acceleration:magnitude_spectrum:spectral_entropy", "raw_acc:magnitude_spectrum:log_energy_band3", "watch_acceleration:3d:std_z", "proc_gyro:magnitude_stats:percentile75", "location:log_longitude_range", "raw_acc:magnitude_spectrum:log_energy_band0", "raw_acc:magnitude_spectrum:log_energy_band4", "watch_acceleration:magnitude_spectrum:log_energy_band3", "raw_acc:magnitude_stats:moment3", "proc_gyro:3d:std_y", "raw_acc:magnitude_stats:percentile75", "proc_gyro:magnitude_stats:std", "watch_acceleration:magnitude_spectrum:log_energy_band2", "discrete:wifi_status:is_reachable_via_wifi", "discrete:time_of_day:between21and3", "watch_acceleration:magnitude_spectrum:log_energy_band1", "raw_acc:magnitude_stats:percentile25", "raw_acc:magnitude_stats:moment4", "raw_acc:magnitude_stats:std", "watch_acceleration:3d:std_y", "raw_acc:3d:std_z", "watch_acceleration:magnitude_stats:moment4", "watch_acceleration:spectrum:z_log_energy_band1"];
    graphNode = GraphNode(labels, features);
    nodes = [nodes graphNode];
    
    labels = "label:OR_standing";
    features = ["watch_heading:mom4_cos", "watch_acceleration:relative_directions:avr_cosine_similarity_lag_range1", "watch_acceleration:spectrum:z_log_energy_band3", "watch_acceleration:relative_directions:avr_cosine_similarity_lag_range2", "watch_heading:mom4_sin", "watch_acceleration:spectrum:z_log_energy_band2", "watch_acceleration:3d:std_x", "watch_acceleration:spectrum:x_log_energy_band0", "watch_acceleration:spectrum:z_log_energy_band4", "watch_heading:entropy_8bins", "audio_naive:mfcc4:std", "watch_acceleration:3d:std_z", "watch_heading:std_sin", "proc_gyro:magnitude_stats:moment3", "watch_acceleration:magnitude_spectrum:log_energy_band3", "proc_gyro:3d:std_y", "proc_gyro:magnitude_stats:std", "watch_acceleration:magnitude_spectrum:log_energy_band2", "audio_naive:mfcc1:std", "audio_naive:mfcc3:std", "watch_acceleration:relative_directions:avr_cosine_similarity_lag_range3", "watch_acceleration:magnitude_spectrum:log_energy_band1", "watch_acceleration:3d:std_y", "watch_acceleration:magnitude_stats:moment4", "watch_acceleration:spectrum:z_log_energy_band1"];
    graphNode = GraphNode(labels, features);
    nodes = [nodes graphNode];
end

