function nodes = createNodes_mi() 
    nodes = [];
    labels = "label:LYING_DOWN";
    features = ["lf_measurements:battery_level", "lf_measurements:temperature_ambient", ...
       "audio_properties:max_abs_value", "audio_naive:mfcc12:std", ...
       "raw_magnet:3d:mean_y"];
    graphNode = GraphNode(labels, features);
    nodes = [nodes graphNode];
    
    labels = "label:SIWTTING";
    features = ["discrete:time_of_day:between21and3", ...
        "raw_magnet:3d:mean_y", ...
        "lf_measurements:temperature_ambient", ...
        "proc_gyro:3d:ro_yz", ...
        "raw_magnet:3d:mean_x", ...
        "audio_properties:max_abs_value"];
    graphNode = GraphNode(labels, features);
    nodes = [nodes graphNode];
    
    labels = "label:FIX_walking";
    features = ["raw_acc:magnitude_stats:value_entropy", ...
        "raw_acc:magnitude_spectrum:log_energy_band1", ...
        "proc_gyro:magnitude_stats:percentile50", ...
        "raw_acc:3d:ro_yz", ...
        "proc_gyro:3d:mean_z"];
    graphNode = GraphNode(labels, features);
    nodes = [nodes graphNode];
    
    labels = "label:FIX_running";
    features = ["lf_measurements:proximity", ...
        "discrete:battery_state:missing", ...
        "lf_measurements:screen_brightness", ...
        "discrete:battery_plugged:is_wireless", ...
        "discrete:wifi_status:is_not_reachable", ...
        "location:min_speed", ...
        "lf_measurements:pressure", ...
        "lf_measurements:light"];
    graphNode = GraphNode(labels, features);
    nodes = [nodes graphNode];
    
    labels = "label:BICYCLING";
    features = ["location:min_speed", ...
        "proc_gyro:magnitude_stats:moment4", ...
        "discrete:wifi_status:is_not_reachable", ...
        "watch_acceleration:magnitude_spectrum:log_energy_band3", ...
        "raw_acc:magnitude_stats:value_entropy"];
    graphNode = GraphNode(labels, features);
    nodes = [nodes graphNode];
    
    labels = "label:OR_standing";
    features = ["lf_measurements:battery_level", ...
        "lf_measurements:screen_brightness", ...
        "raw_magnet:3d:mean_y", ...
        "lf_measurements:proximity", ...
        "raw_magnet:magnitude_stats:percentile25"];
    graphNode = GraphNode(labels, features);
    nodes = [nodes graphNode];
end

