classdef LabelsHandler
    properties
        LabelNames = ["label:LYING_DOWN", ...
        "label:SITTING", ...
        "label:FIX_walking", ...
        "label:FIX_running", ...
        "label:BICYCLING", ...
        "label:SLEEPING", ...
        "label:PHONE_ON_TABLE", ...
        "label:LOC_home", ...
        "label:IN_A_MEETING", ...
        "label:WITH_FRIENDS", ...
        "label:EATING", ...
        "label:SURFING_THE_INTERNET", ...
        "label:OR_outside", ...
        "label:IN_A_CAR"];
    end
    
    methods
        function obj = LabelsHandler()
        end
        
        function index = GetLabelIndex(obj, labelDescription)
            [~, index] = intersect(obj.LabelNames, labelDescription, "stable");
        end
    end

end